apiVersion: v1
kind: Service
metadata:
  name: my-grafana
spec:
  selector:
    app: grafana
  type: LoadBalancer
  loadBalancerSourceRanges:
  - "128.141.0.0/16" 
  ports:
  - name: grafana
    protocol: TCP
    port: 3000
    targetPort: 3000

