apiVersion: v1
kind: Service
metadata:
  name: influx
spec:
  selector:
    app: influx
  type: LoadBalancer
  loadBalancerSourceRanges:
  - "128.141.0.0/16" 
  ports:
  - protocol: TCP
    name: influx
    port: 8086
    targetPort: 8086
  - protocol: TCP
    name: graphite
    port: 2003
    targetPort: 2003

